export const SET_CURRENTMATCHES = "SET_POSITION";
export const SET_CURRENTMATCHESWOMEN = "SET_POSITION";
export const SET_CURRENTMATCHESMEN = "SET_POSITION";
export const SET_ISMATCHTODAYHOME = "SET_POSITION";
export const SET_LIVEBACKGROUDCOLORHOME = "SET_POSITION";
export const SET_SETTINGS = "SET_POSITION";

